sudo: false

language: cpp

cache:
  apt: true

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-4.8
    - g++-4.8
    - cmake
    - cmake-data
    - libboost1.55-all-dev

compiler:
  - g++
  - clang

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - if [ "$CC" = "gcc" ]; then export CXX="gcc-4.8"; fi
#  - mkdir my_path
#  - cd my_path
#  - ln -s /usr/bin/gcc-4-8 ./gcc
#  - ln -s /usr/bin/g++-4-8 ./g++
#  - export PATH=$PWD:$PATH
#  - cd ..

script:
  - source .travis-build.sh
