sudo: false

language: cpp

cache:
  apt: true

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - gcc-4.9
    - g++-4.9
    - libboost1.55-all-dev
    - cmake
    - cmake-data

compiler:
  - g++
  - clang

script:
  - source .travis-build.sh
