sudo: false

cache:
  apt: true
  ccache: true

language: generic
#os: osx
matrix:
  include:
    - os: linux
      env:
        - COMPILER_NAME=gcc
        - CXX=g++-5
        - CC=gcc-5
        - FAST_MATRIX=1
      dist: trusty
      addons:
        apt:
          packages:
            - g++-5
            - cmake
            - cmake-data
            - python3
            - python
          sources: &sources
            #- llvm-toolchain-precise-3.8
            #- george-edison55-precise-backports
            - ubuntu-toolchain-r-test
    - os: osx
      env:
        - FAST_MATRIX=1
    - os: osx
      osx_image: xcode9.1
      env:
        - FAST_MATRIX=1
#    - os: linux
#      env:
#        - COMPILER_NAME=clang
#        - CXX=clang++-3.8
#        - CC=clang-3.8
#      dist: trusty
#      addons:
#        apt:
#          packages:
#            - clang-3.8
#            - cmake
#            - cmake-data
#            - python3
#            - python
#          sources: *sources
before_install: |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install python3;

        # This step needed on osx 10.10 image
        #sudo pip install virtualenv;

        virtualenv venv -p python3;
        source venv/bin/activate;
    fi
script:
  - ./etc/travis_build.sh
