sudo: false

language: cpp

cache:
  apt: true

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - gcc-4.8
    - g++-4.8
    - libboost1.55-all-dev
    - cmake
    - cmake-data

compiler:
  - g++
  - clang

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

script:
  - source .travis-build.sh
