language: cpp
#before_install:
#  - sudo apt-get -qq update
#  - sudo apt-get install -y libboost-all-dev libgoogle-glog-dev
script:
  - wget --no-verbose --output-document=boost-trunk.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2/download
  - export BOOST_ROOT="$TRAVIS_BUILD_DIR/../boost-trunk"
  - mkdir -p $BOOST_ROOT
  - tar jxf boost-trunk.tar.bz2 --strip-components=1 -C $BOOST_ROOT
  - (cd $BOOST_ROOT; ./bootstrap.sh --with-libraries=filesystem,system,iostreams,program_options)
  - (cd $BOOST_ROOT; ./b2 threading=multi --prefix=$BOOST_ROOT -d0 install)
  - git clone https://github.com/google/glog.git
  - export GLOG_ROOT="$TRAVIS_BUILD_DIR/../glog"
  - export GLOG_ROOT_INSTALL="$GLOG_ROOT-install"
  - mkdir -p $GLOG_ROOT_INSTALL
  - pushd $GLOG_ROOT
  - mkdir build
  - pushd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=%GLOG_ROOT_INSTALL ..
  - make
  - make install
  - popd build
  - popd
  - export CMAKE_MODULE_PATH="$BOOST_ROOT $GLOG_ROOT_INSTALL"
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - make check
