# Fast running example config that compares a bunch of
# compression commands on a source file in the repo
[example]
compare_commands = true
with_mem = false
inputs = [
    "$DATASETS/../src/tudocomp_driver/tudocomp_driver.cpp",
    "$DATASETS/download/real/english.50MB",
    "$DATASETS/download/real/sources.50MB",
    "$DATASETS/download/real/dblp.xml.50MB",
    "$DATASETS/download/real/proteins.50MB",
    "$DATASETS/download/real/dna.50MB",
]
commands = [
#      <shown command and args>                 <hidden args>
    ["tudocomp_driver -a lzw.bit",         "-r $IN -o $OUT"],
    ["tudocomp_driver -a lz78.bit",        "-r $IN -o $OUT"],
    ["tudocomp_driver -a lz77ss_lcp.online.online", "-r $IN -o $OUT"],
    ["tudocomp_driver -a lz77ss_lcp.online.offline", "-r $IN -o $OUT"],
    ["tudocomp_driver -a lz77ss_lcp.offline.online", "-r $IN -o $OUT"],
    ["tudocomp_driver -a lz77ss_lcp.offline.offline", "-r $IN -o $OUT"],
    ["tudocomp_driver -a lz77ss.online.online", "-r $IN -o $OUT"],
    ["tudocomp_driver -a lz77ss.online.offline", "-r $IN -o $OUT"],
    ["tudocomp_driver -a lz77ss.offline.online", "-r $IN -o $OUT"],
    ["tudocomp_driver -a lz77ss.offline.offline", "-r $IN -o $OUT"],

    ["gzip -9",                              "-c $IN > $OUT"],
    ["bzip2 -9",                             "-c $IN > $OUT"],
    # 7z prints to stdout per default
    ["7z",                          "a $OUT $IN > /dev/null"],
]

[example2]
compare_commands = false
with_mem = true
inputs = [
    "$DATASETS/../src/tudocomp_driver/tudocomp_driver.cpp",
    "$DATASETS/download/real/english.50MB",
    "$DATASETS/download/real/sources.50MB",
    "$DATASETS/download/real/dblp.xml.50MB",
    "$DATASETS/download/real/proteins.50MB",
    "$DATASETS/download/real/dna.50MB",
]
commands = [
#      <shown command and args>                 <hidden args>
    ["tudocomp_driver -a lzw.bit",         "-r $IN -o $OUT"],
]

[lz78]
inputs = [
    "$DATASETS/../src/tudocomp_driver/tudocomp_driver.cpp",
    "$DATASETS/download/real/english.50MB",
    "$DATASETS/download/real/english.200MB",
]
commands = [
    ["tudocomp_driver -a lz78.bit",   "$IN -o $OUT"],
    ["tudocomp_driver -a lz78.debug", "$IN -o $OUT"],
]
