# Fast running example config that compares a bunch of
# compression commands on a source file in the repo
[example_fast]
compare_commands = true
with_mem = false
inputs = [
    "$DATASETS/../src/tudocomp_driver/main.cpp",
]
commands = [
#      <shown command and args>                     <hidden args>    <out file ending>
    ["tudocomp_driver -a lz78rule.lz78.debug",      "$IN -o $OUT",   "lz78rule.lz78.debug.tdc"     ],
    ["tudocomp_driver -a lz78rule.lz78.bit",        "$IN -o $OUT",   "lz78rule.lz78.bit.tdc"       ],
    ["tudocomp_driver -a lz77rule.dummy.dummy",     "$IN -o $OUT",   "lz77rule.dummy.dummy.tdc"    ],
    ["tudocomp_driver -a lz77rule.dummy.esa_code0", "$IN -o $OUT",   "lz77rule.dummy.esa_code0.tdc"],
    ["tudocomp_driver -a lz77rule.dummy.esa_code1", "$IN -o $OUT",   "lz77rule.dummy.esa_code1.tdc"],
    ["tudocomp_driver -a lz77rule.dummy.esa_code2", "$IN -o $OUT",   "lz77rule.dummy.esa_code2.tdc"],
    ["tudocomp_driver -a lz77rule.lz.esa_code2",    "$IN -o $OUT",   "lz77rule.lz.esa_code2.tdc"   ],
    ["tudocomp_driver -a lz77rule.esa.esa_code2",   "$IN -o $OUT",   "lz77rule.esa.esa_code2.tdc"  ],

    ["gzip -9",                                     "-c $IN > $OUT", "gz"                          ],
    ["bzip2 -9",                                    "-c $IN > $OUT", "bz2"                         ],
    # 7z prints to stdout per default
    ["7z",                                          "a $OUT $IN > /dev/null", "7z"                 ],

    ["tudocomp_driver -a lz77rule.lz.esa_code1",    "$IN -o $OUT",   "lz77rule.lz.esa_code1.tdc"   ],
    ["tudocomp_driver -a lz77rule.esa.esa_code1",   "$IN -o $OUT",   "lz77rule.esa.esa_code1.tdc"  ],
    ["tudocomp_driver -a lz77rule.lz.dummy",        "$IN -o $OUT",   "lz77rule.lz.dummy.tdc"       ],
]

# Same as example_fast, but also measuring memory usage
[example_fast_mem]
inherit_from = "example_fast"
with_mem = true

# Compare a number of different text files with the same algorithms
[example_compare_texts]
compare_commands = false
inputs = [
    "$DATASETS/download/real/english.50MB",
    "$DATASETS/download/real/sources.50MB",
    "$DATASETS/download/real/dblp.xml.50MB",
    "$DATASETS/download/real/proteins.50MB",
    "$DATASETS/download/real/dna.50MB",
]
commands = [
    ["tudocomp_driver -a lz78rule.lz78.bit",        "$IN -o $OUT",   "lz78rule.lz78.bit.tdc"       ],
    ["tudocomp_driver -a lz77rule.esa.esa_code2", "$IN -o $OUT",   "lz77rule.esa.code2.tdc"],
    ["gzip -9",                                   "-c $IN > $OUT", "gz"                    ],
    ["bzip2 -9",                                  "-c $IN > $OUT", "bz2"                   ],
    ["7z",                                        "a $OUT $IN",    "7z"                    ],
]
