# Fast running example config that compares a bunch of
# compression commands on a simple 1MB pseudo-english textfile.
[example_fast]
compare_commands = true
with_mem = false
inputs = [
    "$DATASETS/alice_markov.1MB",
]
commands = [
#      <shown command and args>               <hidden args>    <out file ending>
    ["tudocomp_driver -c dummy -e dummy",     "$IN -o $OUT",   "dummy.dummy.tdc"    ],
    ["tudocomp_driver -c dummy -e esa_code0", "$IN -o $OUT",   "dummy.esa_code0.tdc"],
    ["tudocomp_driver -c dummy -e esa_code1", "$IN -o $OUT",   "dummy.esa_code1.tdc"],
    ["tudocomp_driver -c dummy -e esa_code2", "$IN -o $OUT",   "dummy.esa_code2.tdc"],
    ["tudocomp_driver -c lz -e esa_code2",    "$IN -o $OUT",   "lz.esa_code2.tdc"   ],
    ["tudocomp_driver -c esa -e esa_code2",   "$IN -o $OUT",   "esa.esa_code2.tdc"  ],
    ["gzip -9",                               "-c $IN > $OUT", "gz"                 ],
    ["bzip2 -9",                              "-c $IN > $OUT", "bz2"                ],
    ["7z",                                    "a $OUT $IN",    "7z"                 ],
    ["tudocomp_driver -c lz -e esa_code1",    "$IN -o $OUT",   "lz.esa_code1.tdc"   ],
    ["tudocomp_driver -c esa -e esa_code1",   "$IN -o $OUT",   "esa.esa_code1.tdc"  ],
]

# Same as example_fast, but also measuring memory usage
[example_fast_mem]
inherit_from = "example_fast"
with_mem = true

# Compare a number of different text files with the same algorithms
[example_compare_texts]
compare_commands = false
inputs = [
    "$DATASETS/download/real/english.50MB",
    "$DATASETS/download/real/sources.50MB",
    "$DATASETS/download/real/dblp.xml.50MB",
    "$DATASETS/download/real/proteins.50MB",
    "$DATASETS/download/real/dna.50MB",
]
commands = [
    ["tudocomp_driver -c esa -e esa_code2",   "$IN -o $OUT",   "esa.code2.tdc"  ],
    ["gzip -9",                               "-c $IN > $OUT", "gz"             ],
    ["bzip2 -9",                              "-c $IN > $OUT", "bz2"            ],
    ["7z",                                    "a $OUT $IN",    "7z"             ],
]
